export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS';
export const GET_CONTACT_FAIL = 'GET_CONTACT_FAIL';
export const GET_CONTACT_LOADING = 'GET_CONTACT_LOADING';

export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_FAIL = 'CREATE_CONTACT_FAIL';
export const CREATE_CONTACT_LOADING = 'CREATE_CONTACT_LOADING';
export const CLEAR_CONTACT = 'CLEAR_CONTACT';

export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL';
export const DELETE_CONTACT_LOADING = 'DELETE_CONTACT_LOADING';

export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS';
export const EDIT_CONTACT_FAIL = 'EDIT_CONTACT_FAIL';
export const EDIT_CONTACT_LOADING = 'EDIT_CONTACT_LOADING';

export const CREATE_IMAGE_SUCCESS = 'CREATE_IMAGE_SUCCESS';
export const CREATE_IMAGE_FAIL = 'CREATE_IMAGE_FAIL';
export const CREATE_IMAGE_LOADING = 'CREATE_IMAGE_LOADING';
